/**
 * API Delivery Manager
 * API Delivery Manager
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Customer information
 */
export interface Customer {
  /**
   * Customer id
   */
  id?: string;
  /**
   * Customer name
   */
  name?: string;
  /**
   * Customer email
   */
  email?: string;
  /**
   * Customer phone
   */
  phoneNumber?: string;
  /**
   * Customer address
   */
  address?: string;
}
