/**
 * API Delivery Manager
 * API Delivery Manager
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Jwt Token
 */
export interface Kpis {
  /**
   * Total orders kpi
   */
  totalOrders?: number;
  /**
   * Finished orders kpi
   */
  finishedOrders?: number;
  /**
   * In preparation orders kpi
   */
  inPreparationOrders?: number;
  /**
   * Average preparation time kpi
   */
  averagePreparationTime?: number;
  /**
   * Min preparation time kpi
   */
  minPreparationTime?: number;
  /**
   * Max preparation time kpi
   */
  maxPreparationTime?: number;
  /**
   * Awaiting orders kpi
   */
  awaitingOrders?: number;
  /**
   * Orders in delivery
   */
  inDeliveryOrders?: number;
  /**
   * Average delivery time
   */
  averageDeliveryTime?: number;
  /**
   * Minimum delivery time
   */
  minDeliveryTime?: number;
  /**
   * Max delivery time
   */
  maxDeliveryTime?: number;
  /**
   * Average total time
   */
  averageEndToEndTime?: number;
  /**
   * Minimum total time
   */
  minEndToEndTime?: number;
  /**
   * Max total time
   */
  maxEndToEndTime?: number;
  /**
   * Total pickup orders
   */
  pickupOrders?: number;
  /**
   * Total delivered orders
   */
  deliveredOrders?: number;
  /**
   * Most selled product
   */
  mostSelledProduct?: string;
  /**
   * Total selled products
   */
  selledProducts?: Array<[string, number]>;
}
