/**
 * API Delivery Manager
 * API Delivery Manager
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Rider information
 */
export interface Rider {
  /**
   * Rider id
   */
  id?: string;
  /**
   * Rider name
   */
  name?: string;
  /**
   * Rider phone
   */
  phone?: string;
}
