/**
 * API Delivery Manager
 * API Delivery Manager
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Status update
 */
export interface StatusUpdate { 
    /**
     * Status enum
     */
    status?: StatusUpdate.StatusEnum;
}
export namespace StatusUpdate {
    export type StatusEnum = 'PENDING' | 'IN_PROGRESS' | 'PREPARED' | 'READY' | 'IN_DELIVERY' | 'DELIVERED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        INPROGRESS: 'IN_PROGRESS' as StatusEnum,
        PREPARED: 'PREPARED' as StatusEnum,
        READY: 'READY' as StatusEnum,
        INDELIVERY: 'IN_DELIVERY' as StatusEnum,
        DELIVERED: 'DELIVERED' as StatusEnum
    };
}