/**
 * API Delivery Manager
 * API Delivery Manager
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Subitem information
 */
export interface SubItem { 
    /**
     * Subitem id
     */
    id?: string;
    /**
     * Subitem name
     */
    name?: string;
    /**
     * Subitem plu
     */
    plu?: string;
    /**
     * Subitem price in cents without decimals
     */
    price?: number;
    /**
     * Subitem quantity
     */
    quantity?: number;
}